config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { in: 6..100 }
  validates :description, presence: true, length: { in: 10..300 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :find_article, only: [:show, :edit, :update, :destroy]

  def show
  end

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(get_valid_params)
    if @article.save
      flash.notice = "Article is successfully saved!"
      redirect_to @article
    else
      render "new"
    end
  end

  def update
    if @article.update(get_valid_params)
      flash.notice = "Article is successfully updated!"
      redirect_to @article
    else
      render "edit"
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def find_article
    @article = Article.find(params[:id])
  end

  def get_valid_params
    params.require(:article).permit(:title, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <h2>Please resolve the following errors: </h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: @article, local: true) do |form| %>
  <p>
    <%= form.label :title, "Title" %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :description, "Description" %><br>
    <%= form.text_area :description %>
  </p>
  <%= form.submit %>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form" %>

<%= link_to "Cancel and return to all articles", articles_path %>

app/views/articles/index.html.erb
<h1>Show All Articles</h1>

<table>
  <thead>
    <tr>
      <th>title</th>
      <th>description</th>
      <th colspan="3">action</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.description %></td>
      <td><%= link_to "SHOW", article_path(article) %></td>
      <td><%= link_to "EDIT", edit_article_path(article) %></td>
      <td><%= link_to "DELETE", article_path(article), method: :delete, data: { confirm: "Are you sure?" } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<p>
  <%= link_to "Create new article", new_article_path %> |
  <%= link_to "HOME", root_path %>
</p>

app/views/articles/new.html.erb
<h1>Create Article</h1>

<%= render "form" %>

<%= link_to "Back to all articles", articles_path %>

app/views/articles/show.html.erb
<h1>Show Article Details</h1>

<p><strong>Title: </strong><%= @article.title %></p>
<p><strong>Description: </strong><%= @article.description %></p>

<%= link_to "EDIT", edit_article_path(@article) %> |
<%= link_to "DELETE", article_path(@article), method: :delete, data: { confirm: "Are you sure?" } %> |
<%= link_to "Back to all articles", articles_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <%= msg %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/messages" %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the About page.</h1>

<%= link_to "HOME", root_path %>

app/views/pages/home.html.erb
<h1>This is the Home page.</h1>

<%= link_to "All articles", articles_path %> |
<%= link_to "ABOUT", about_path %>